#!/usr/bin/env bash
# Assemble the published matter-sdk-go tree: Go sources, C header, one prebuilt static
# archive per platform, and a generated link.go selecting among them.
#
#   usage: scripts/assemble-go-module.sh <libs-dir> <out-dir> [--partial]
#     <libs-dir>  archives from scripts/build-ffi-staticlib.sh
#     --partial   skip platforms whose archive is missing (local runs); without it, a missing archive fails
#
# Deterministic: same inputs give a byte-identical tree, so release re-runs compare equal.
set -euo pipefail
readonly USAGE='usage: assemble-go-module.sh <libs-dir> <out-dir> [--partial]'
libs=$(realpath "${1:?$USAGE}")
out=$(realpath -m "${2:?$USAGE}")
case "${3:-}" in
  '') partial=false ;;
  --partial) partial=true ;;
  *) echo "$USAGE" >&2; exit 2 ;;
esac
cd "$(dirname "$0")/.."
# shellcheck source=scripts/lib-targets.sh
source scripts/lib-targets.sh

readonly PACKAGE=packages/go/mattersdk
readonly HEADER=crates/matter-sdk-ffi/include/matter_sdk.h
readonly DEV_LINK_FILE=link_dev.go # monorepo-only; the published module gets link.go
readonly SOURCE_REPO=https://github.com/OpenMatter-Network/matter-sdk

# Keep .git: the publish step assembles into a clone of matter-sdk-go.
mkdir -p "$out"
find "$out" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

# Archives and header go at the module root: `go mod vendor` copies only imported package
# dirs, and module zips drop any `vendor` directory.
find "$PACKAGE" -maxdepth 1 -type f \( -name '*.go' -o -name go.mod -o -name go.sum \) ! -name "$DEV_LINK_FILE" \
  -exec cp {} "$out"/ \;
cp -RL "$PACKAGE/testdata" "$out/testdata" # -L: the monorepo's testdata/vectors is a symlink
cp "$HEADER" LICENSE "$out"/

shipped=()
while read -r id; do
  archive=$(target_archive "$id")
  if [ -f "$libs/$archive" ]; then
    install -m 644 "$libs/$archive" "$out/$archive"
    shipped+=("$id")
  elif [ "$partial" = false ]; then
    echo "assemble-go-module: $libs/$archive is missing (pass --partial for a local subset)" >&2
    exit 1
  fi
done < <(target_ids)
[ "${#shipped[@]}" -gt 0 ] || { echo "assemble-go-module: no archives found in $libs" >&2; exit 1; }
shipped_json=$(printf '%s\n' "${shipped[@]}" | jq -R . | jq -sc .)

# Go has no GOOS for musl, so musl rows are selected by -tags musl.
rows() { jq -r --argjson shipped "$shipped_json" "[.[] | select(.id as \$id | \$shipped | index(\$id))] | $1" "$TARGETS_FILE"; }
readonly CONSTRAINT='"\(.goos),\(.goarch)" + ({"glibc": ",!musl", "musl": ",musl"}[.libc] // "")'
supported=$(rows 'map("\(.goos)/\(.goarch)" + (if .libc == "" then "" else " (\(.libc))" end)) | join(", ")')

{
  echo "// Code generated by scripts/assemble-go-module.sh from scripts/native-targets.json; DO NOT EDIT."
  echo "// Source: $SOURCE_REPO @ $(git describe --always --dirty --abbrev=12)"
  echo
  echo "package mattersdk"
  echo
  echo "/*"
  rows ".[] | ($CONSTRAINT) as \$c | \"#cgo \(\$c) LDFLAGS: \${SRCDIR}/${FFI_LIB_STEM}_\(.id).a \(.ldflags)\n#cgo \(\$c) CFLAGS: -DMSDK_HAVE_PREBUILT\""
  cat <<EOF
#cgo musl CFLAGS: -DMSDK_TAG_MUSL

#ifndef MSDK_HAVE_PREBUILT
#error "matter-sdk-go: no prebuilt core for this platform. Supported: $supported."
#endif

// Go cannot tell glibc from musl, so the tag is the only signal — and a wrong one links
// the wrong archive and fails with a wall of undefined symbols. Ask the C library instead.
#ifdef __linux__
#include <features.h>
#if defined(MSDK_TAG_MUSL) && defined(__GLIBC__)
#error "matter-sdk-go: -tags musl is set, but this system's libc is glibc; remove the tag."
#elif !defined(MSDK_TAG_MUSL) && !defined(__GLIBC__)
#error "matter-sdk-go: this system's libc is not glibc; on Alpine/musl build with -tags musl."
#endif
#endif
*/
import "C"
EOF
} >"$out/link.go"

# README: drop the monorepo-only section; make relative links absolute.
sed -e '/<!-- monorepo-only -->/,/<!-- \/monorepo-only -->/d' \
  -e "s|](\.\./\.\./\.\./|]($SOURCE_REPO/blob/main/|g" "$PACKAGE/README.md" >"$out/README.md"

# Self-check for what a module zip would silently drop or a consumer would trip on.
bad() { echo "assemble-go-module: $1" >&2; exit 1; }
[ -z "$(find "$out" -path "$out/.git" -prune -o -type l -print)" ] || bad "the tree contains symlinks, which a module zip omits"
[ ! -e "$out/$DEV_LINK_FILE" ] || bad "$DEV_LINK_FILE must not ship; its paths point into the monorepo"
for id in "${shipped[@]}"; do
  grep -qF "$(target_archive "$id")" "$out/link.go" || bad "link.go does not reference $(target_archive "$id")"
done
echo "assembled $out: ${#shipped[@]} platform(s) — $supported"
