#!/usr/bin/env bash
# Assemble the tree that is published as github.com/openmatter-network/matter-sdk-go: the
# Go sources, the C header, one prebuilt static archive per platform, and a generated
# link.go that selects among them. `go get` cannot run a Rust build, and the core's
# source is private, so this tree is the only form in which the Go binding can ship.
#
#   usage: scripts/assemble-go-module.sh <libs-dir> <out-dir> [--partial]
#     <libs-dir>  archives from scripts/build-ffi-staticlib.sh
#     --partial   emit only the platforms whose archive is present (local runs). Without
#                 it a missing archive is an error: a release never ships a platform short.
#
# Takes no version: the tag carries it. Same inputs give a byte-identical tree, so a
# re-run of a release compares equal to what it already pushed.
set -euo pipefail
readonly USAGE='usage: assemble-go-module.sh <libs-dir> <out-dir> [--partial]'
libs=$(realpath "${1:?$USAGE}")
out=$(realpath -m "${2:?$USAGE}")
case "${3:-}" in
  '') partial=false ;;
  --partial) partial=true ;;
  *) echo "$USAGE" >&2; exit 2 ;;
esac
cd "$(dirname "$0")/.."
# shellcheck source=scripts/lib-targets.sh
source scripts/lib-targets.sh

readonly PACKAGE=packages/go/mattersdk
readonly HEADER=crates/matter-sdk-ffi/include/matter_sdk.h
readonly DEV_LINK_FILE=link_dev.go # the monorepo's link flags; the published module gets link.go
readonly SOURCE_REPO=https://github.com/OpenMatter-Network/matter-sdk

# Everything but .git goes: the publish step assembles into a clone of matter-sdk-go.
mkdir -p "$out"
find "$out" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +

# Sources. Archives and header sit at the module ROOT beside them: `go mod vendor` copies
# only the files of imported package directories, -I${SRCDIR} is implied, and Go's module
# zip drops any directory named `vendor`.
find "$PACKAGE" -maxdepth 1 -type f \( -name '*.go' -o -name go.mod -o -name go.sum \) ! -name "$DEV_LINK_FILE" \
  -exec cp {} "$out"/ \;
cp -RL "$PACKAGE/testdata" "$out/testdata" # -L: the monorepo's testdata/vectors is a symlink
cp "$HEADER" LICENSE "$out"/

shipped=()
while read -r id; do
  archive=$(target_archive "$id")
  if [ -f "$libs/$archive" ]; then
    install -m 644 "$libs/$archive" "$out/$archive"
    shipped+=("$id")
  elif [ "$partial" = false ]; then
    echo "assemble-go-module: $libs/$archive is missing (pass --partial for a local subset)" >&2
    exit 1
  fi
done < <(target_ids)
[ "${#shipped[@]}" -gt 0 ] || { echo "assemble-go-module: no archives found in $libs" >&2; exit 1; }
shipped_json=$(printf '%s\n' "${shipped[@]}" | jq -R . | jq -sc .)

# One cgo line pair per platform. The constraint is derived from the row: Go has no GOOS
# for "musl", so Alpine users pass -tags musl — confluent-kafka-go's convention.
rows() { jq -r --argjson shipped "$shipped_json" "[.[] | select(.id as \$id | \$shipped | index(\$id))] | $1" "$TARGETS_FILE"; }
readonly CONSTRAINT='"\(.goos),\(.goarch)" + ({"glibc": ",!musl", "musl": ",musl"}[.libc] // "")'
supported=$(rows 'map("\(.goos)/\(.goarch)" + (if .libc == "" then "" else " (\(.libc))" end)) | join(", ")')

{
  echo "// Code generated by scripts/assemble-go-module.sh from scripts/native-targets.json; DO NOT EDIT."
  echo "// Source: $SOURCE_REPO @ $(git describe --always --dirty --abbrev=12)"
  echo
  echo "package mattersdk"
  echo
  echo "/*"
  rows ".[] | ($CONSTRAINT) as \$c | \"#cgo \(\$c) LDFLAGS: \${SRCDIR}/${FFI_LIB_STEM}_\(.id).a \(.ldflags)\n#cgo \(\$c) CFLAGS: -DMSDK_HAVE_PREBUILT\""
  cat <<EOF
#cgo musl CFLAGS: -DMSDK_TAG_MUSL

#ifndef MSDK_HAVE_PREBUILT
#error "matter-sdk-go: no prebuilt core for this platform. Supported: $supported."
#endif

// Go cannot tell glibc from musl, so the tag is the only signal — and a wrong one links
// the wrong archive and fails with a wall of undefined symbols. Ask the C library instead.
#ifdef __linux__
#include <features.h>
#if defined(MSDK_TAG_MUSL) && defined(__GLIBC__)
#error "matter-sdk-go: -tags musl is set, but this system's libc is glibc; remove the tag."
#elif !defined(MSDK_TAG_MUSL) && !defined(__GLIBC__)
#error "matter-sdk-go: this system's libc is not glibc; on Alpine/musl build with -tags musl."
#endif
#endif
*/
import "C"
EOF
} >"$out/link.go"

# README: drop the monorepo-only section, and point its relative links at the source repo.
sed -e '/<!-- monorepo-only -->/,/<!-- \/monorepo-only -->/d' \
  -e "s|](\.\./\.\./\.\./|]($SOURCE_REPO/blob/main/|g" "$PACKAGE/README.md" >"$out/README.md"

# Self-check: what would break a consumer, and what Go's module zip would silently drop.
bad() { echo "assemble-go-module: $1" >&2; exit 1; }
[ -z "$(find "$out" -path "$out/.git" -prune -o -type l -print)" ] || bad "the tree contains symlinks, which a module zip omits"
[ ! -e "$out/$DEV_LINK_FILE" ] || bad "$DEV_LINK_FILE must not ship; its paths point into the monorepo"
for id in "${shipped[@]}"; do
  grep -qF "$(target_archive "$id")" "$out/link.go" || bad "link.go does not reference $(target_archive "$id")"
done
echo "assembled $out: ${#shipped[@]} platform(s) — $supported"
